// Generated version information
// This file is auto-generated by sync-version.ts

/**
 * AdCP SDK library version
 */
export const LIBRARY_VERSION = '14.0.0-beta.4';

/**
 * AdCP specification version this library is built for
 */
export const ADCP_VERSION = '3.2.0-beta.3';

/**
 * AdCP major version sent with every request (adcp_major_version field).
 * Sellers validate this against their supported versions and return
 * VERSION_UNSUPPORTED if the version is not in range.
 */
export const ADCP_MAJOR_VERSION = 3;

/**
 * AdCP versions this library maintains backward compatibility with.
 *
 * Auto-derived from `ADCP_VERSION` by scripts/sync-version.ts. Do not edit
 * this list by hand; bumping the AdCP pin via `npm run sync-version`
 * extends it.
 */
export const COMPATIBLE_ADCP_VERSIONS = [
  'v2.5',
  'v2.6',
  'v3',
  '3.0.0-beta.1',
  '3.0-beta.1',
  '3.0-beta',
  '3.0.0-beta.3',
  '3.0-beta.3',
  '3.0.0',
  '3.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '3.0.4',
  '3.0.5',
  '3.0.6',
  '3.0.7',
  '3.0.8',
  '3.0.9',
  '3.0.10',
  '3.0.11',
  '3.0.12',
  '3.0.13',
  '3.0.14',
  '3.0.15',
  '3.0.16',
  '3.0.17',
  '3.0.18',
  '3.0.19',
  '3.0.20',
  '3.0.21',
  '3.0.22',
  '3.0.23',
  '3.0.24',
  '3.1.0',
  '3.1',
  '3.1.1',
  '3.1.2',
  '3.1.3',
  '3.1.4',
  '3.1.5',
  '3.1.6',
  '3.1.7',
  '3.1.8',
  '3.1.9',
  '3.1.10',
  '3.1.11',
  '3.1.12',
  '3.1.13',
  '3.1.14',
  '3.1.15',
  '3.2.0-beta.3',
  '3.2-beta.3',
] as const;

/**
 * String literal union of every AdCP version the SDK formally supports.
 *
 * Used by the per-instance `adcpVersion` constructor option to give callers
 * autocomplete in editors. The intersection with `(string & {})` in the
 * config type preserves the escape hatch — any string is still accepted at
 * the type level — while the literal union surfaces canonical values first.
 */
export type AdcpVersion = (typeof COMPATIBLE_ADCP_VERSIONS)[number];

/**
 * Full version information
 */
export const VERSION_INFO = {
  library: '14.0.0-beta.4',
  adcp: '3.2.0-beta.3',
  compatibleVersions: COMPATIBLE_ADCP_VERSIONS,
  generatedAt: '2026-08-20T06:59:41.487Z',
} as const;

/**
 * Get the AdCP specification version this library is built for
 */
export function getAdcpVersion(): string {
  return ADCP_VERSION;
}

/**
 * Get the library version
 */
export function getLibraryVersion(): string {
  return LIBRARY_VERSION;
}

/**
 * Check if this library version is compatible with a given AdCP version
 */
export function isCompatibleWith(adcpVersion: string): boolean {
  return (COMPATIBLE_ADCP_VERSIONS as readonly string[]).includes(adcpVersion);
}

/**
 * Get all AdCP versions this library is compatible with
 */
export function getCompatibleVersions(): readonly string[] {
  return COMPATIBLE_ADCP_VERSIONS;
}

/**
 * Extract the major version number from an AdCP version string.
 *
 * Accepts:
 *   - Semver: '3.0.0', '3.0.1', '3.1.0-beta.1' → 3
 *   - Legacy aliases: 'v3' → 3, 'v2.5' / 'v2.6' → 2
 *
 * Returns NaN for unrecognized strings — callers should validate before passing.
 */
export function parseAdcpMajorVersion(version: string): number {
  const trimmed = version.trim();
  const semverLike = trimmed.startsWith('v') ? trimmed.slice(1) : trimmed;
  const major = parseInt(semverLike.split('.')[0] ?? '', 10);
  return Number.isFinite(major) ? major : NaN;
}

/**
 * Normalize a full-semver AdCP version (`MAJOR.MINOR.PATCH[-prerelease]`) to
 * the release-precision form that AdCP 3.1+ requires on the wire:
 * `MAJOR.MINOR[-prerelease]` — the patch digit is dropped.
 *
 * Per the spec note on `adcp_version`: "SDKs that read full-semver values
 * from bundle metadata (e.g. `ComplianceIndex.published_version =
 * "3.1.0-beta.1"`) MUST normalize to release-precision (`"3.1-beta.1"`)
 * before emitting on the wire — meta-field values are NOT valid wire
 * values." The wire regex (`^\d+\.\d+(-[a-zA-Z0-9.-]+)?$`) rejects strings
 * with a patch digit.
 *
 * Behavior:
 *   - `"3.1.0-beta.7"` → `"3.1-beta.7"`
 *   - `"3.1.0"`        → `"3.1"`
 *   - `"3.0.12"`       → `"3.0"`
 *   - Already-release-precision input (`"3.1"`, `"3.1-beta.7"`) passes through
 *   - Legacy aliases (`"v2.5"`, `"v3"`) pass through unchanged — the wire
 *     regex doesn't accept them anyway; the v2.5 path uses
 *     `adcp_major_version` instead of `adcp_version` for transport.
 *   - Unrecognized strings pass through unchanged so callers can detect drift
 *     via the wire validator rather than have it masked by this helper.
 */
export function toReleasePrecisionVersion(version: string): string {
  const trimmed = version.trim();
  // Pre-release form `MAJOR.MINOR.PATCH-prerelease` → `MAJOR.MINOR-prerelease`
  const semverMatch = trimmed.match(/^(\d+)\.(\d+)\.\d+(-[A-Za-z0-9.-]+)?$/);
  if (semverMatch) {
    const [, major, minor, pre = ''] = semverMatch;
    return `${major}.${minor}${pre}`;
  }
  // Already release-precision (no patch digit). Includes `3.1`, `3.1-beta.7`.
  if (/^\d+\.\d+(-[A-Za-z0-9.-]+)?$/.test(trimmed)) return trimmed;
  // Legacy aliases (`v3`, `v2.5`, `v2.6`) and anything we don't recognize —
  // pass through so the wire validator can flag genuine drift.
  return version;
}
