// AUTO-GENERATED by scripts/generate-wire-spec-fields.ts. DO NOT EDIT.
// Source: schemas/cache/3.2.0-beta.3/**/*-request.json
// Generated at: 2026-08-20T05:30:22.885Z

import type {
  AcquireRightsRequest,
  ActivateSignalRequest,
  BuildCreativeRequest,
  CalibrateContentRequest,
  CreateCollectionListRequest,
  CreateContentStandardsRequest,
  CreateMediaBuyRequest,
  CreatePropertyListRequest,
  DeleteCollectionListRequest,
  DeletePropertyListRequest,
  GetMediaBuyDeliveryRequest,
  LogEventRequest,
  ProvidePerformanceFeedbackRequest,
  ReportPlanOutcomeRequest,
  ReportUsageRequest,
  SIInitiateSessionRequest,
  SISendMessageRequest,
  SyncAccountsRequest,
  SyncAudiencesRequest,
  SyncCatalogsRequest,
  SyncCreativesRequest,
  SyncEventSourcesRequest,
  SyncGovernanceRequest,
  SyncPlansRequest,
  UpdateCollectionListRequest,
  UpdateContentStandardsRequest,
  UpdateMediaBuyRequest,
  UpdatePropertyListRequest,
  UpdateRightsRequest,
} from '../types';

/**
 * Wire-spec field allowlists per request type. The `fields` values
 * are exact top-level property names from the AdCP request JSON
 * schemas; `pickWireSpecFields(req, schemaName)` uses them to strip
 * buyer-controlled args to schema-spec fields at the operational
 * fan-out boundary. Drift between this map and the schemas is
 * impossible by construction — both are emitted from the same
 * codegen pass.
 *
 * The `__type` phantom is type-only (`null as unknown as T`) — it
 * carries the wire-spec request shape so `pickWireSpecFields`'s
 * return type narrows per `schemaName`. Runtime cost: one null
 * property per entry.
 *
 * Arrays and entry objects are runtime-frozen via `Object.freeze`
 * so a misbehaving dependency cannot widen the scrub via prototype
 * pollution or shared-state mutation of the allowlist.
 */
export const WIRE_SPEC_FIELDS = Object.freeze({
  /** schemas/cache/3.2.0-beta.3/brand/acquire-rights-request.json */
  AcquireRightsRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","buyer","campaign","context","ext","governance_context","idempotency_key","pricing_option_id","push_notification_config","revocation_webhook","rights_id"]) as readonly string[],
    __type: null as unknown as AcquireRightsRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/profiles/production/signals/activate-signal-request.json */
  ActivateSignalRequest: Object.freeze({
    fields: Object.freeze(["account","action","adcp_major_version","adcp_version","context","destinations","ext","governance_context","idempotency_key","pricing_option_id","signal_agent_segment_id"]) as readonly string[],
    __type: null as unknown as ActivateSignalRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/build-creative-request.json */
  BuildCreativeRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","brand","concept_id","config","context","creative_id","creative_manifest","evaluator","ext","governance_context","idempotency_key","include_preview","item_limit","keep_mode","macro_values","max_creatives","max_spend","max_variants","media_buy_id","message","mode","package_id","preview_inputs","preview_output_format","preview_quality","push_notification_config","quality","refine_from_build_variant_id","selection_strategy","signal_conditions","target_capability_id","target_capability_ids","target_format_id","target_format_ids","transformer_id","variant_axis"]) as readonly string[],
    __type: null as unknown as BuildCreativeRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/content-standards/calibrate-content-request.json */
  CalibrateContentRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","artifact","context","ext","idempotency_key","standards_id"]) as readonly string[],
    __type: null as unknown as CalibrateContentRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/collection/create-collection-list-request.json */
  CreateCollectionListRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","base_collections","brand","context","description","ext","filters","idempotency_key","name"]) as readonly string[],
    __type: null as unknown as CreateCollectionListRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/content-standards/create-content-standards-request.json */
  CreateContentStandardsRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","calibration_exemplars","context","ext","idempotency_key","policies","registry_policy_ids","scope"]) as readonly string[],
    __type: null as unknown as CreateContentStandardsRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/create-media-buy-request.json */
  CreateMediaBuyRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","advertiser_industry","agency_estimate_number","artifact_webhook","bidding","brand","budget_allocation","budget_cap_timezone","context","daily_budget_cap","end_time","ext","governance_context","idempotency_key","invoice_recipient","io_acceptance","name","opportunity","pacing","packages","paused","plan_id","po_number","proposal_id","push_notification_config","reporting_webhook","start_time","total_budget"]) as readonly string[],
    __type: null as unknown as CreateMediaBuyRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/profiles/production/property/create-property-list-request.json */
  CreatePropertyListRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","base_properties","brand","context","description","ext","filters","idempotency_key","name"]) as readonly string[],
    __type: null as unknown as CreatePropertyListRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/collection/delete-collection-list-request.json */
  DeleteCollectionListRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","context","ext","idempotency_key","list_id"]) as readonly string[],
    __type: null as unknown as DeleteCollectionListRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/profiles/production/property/delete-property-list-request.json */
  DeletePropertyListRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","context","ext","idempotency_key","list_id"]) as readonly string[],
    __type: null as unknown as DeletePropertyListRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/get-media-buy-delivery-request.json */
  GetMediaBuyDeliveryRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","attribution_window","context","end_date","ext","include_package_daily_breakdown","include_window_breakdown","media_buy_ids","reporting_dimensions","start_date","status_filter","time_granularity"]) as readonly string[],
    __type: null as unknown as GetMediaBuyDeliveryRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/log-event-request.json */
  LogEventRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","context","event_source_id","events","ext","idempotency_key","test_event_code"]) as readonly string[],
    __type: null as unknown as LogEventRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/provide-performance-feedback-request.json */
  ProvidePerformanceFeedbackRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","as_of","baseline","context","creative_id","evidence","evidence_ref","ext","feedback_source","final","idempotency_key","measurement_period","media_buy_id","methodology","methodology_version","metric","metric_type","package_id","performance_index","producer","study_ref","supersedes_feedback_id","vendor"]) as readonly string[],
    __type: null as unknown as ProvidePerformanceFeedbackRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/governance/report-plan-outcome-request.json */
  ReportPlanOutcomeRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","check_id","context","delivery","error","ext","governance_context","idempotency_key","outcome","plan_id","purchase_type","seller_response"]) as readonly string[],
    __type: null as unknown as ReportPlanOutcomeRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/account/report-usage-request.json */
  ReportUsageRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","context","ext","idempotency_key","reporting_period","usage"]) as readonly string[],
    __type: null as unknown as ReportUsageRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/profiles/production/sponsored-intelligence/si-initiate-session-request.json */
  SIInitiateSessionRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","context","ext","idempotency_key","identity","intent","media_buy_id","offering_id","offering_token","placement","sponsored_context_receipt","supported_capabilities"]) as readonly string[],
    __type: null as unknown as SIInitiateSessionRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/profiles/production/sponsored-intelligence/si-send-message-request.json */
  SISendMessageRequest: Object.freeze({
    fields: Object.freeze(["action_response","adcp_major_version","adcp_version","context","ext","idempotency_key","message","session_id","sponsored_context_receipt"]) as readonly string[],
    __type: null as unknown as SISendMessageRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/account/sync-accounts-request.json */
  SyncAccountsRequest: Object.freeze({
    fields: Object.freeze(["accounts","adcp_major_version","adcp_version","context","delete_missing","dry_run","ext","idempotency_key","push_notification_config"]) as readonly string[],
    __type: null as unknown as SyncAccountsRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/sync-audiences-request.json */
  SyncAudiencesRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","audiences","context","delete_missing","ext","idempotency_key"]) as readonly string[],
    __type: null as unknown as SyncAudiencesRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/sync-catalogs-request.json */
  SyncCatalogsRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","catalog_ids","catalogs","context","delete_missing","dry_run","ext","idempotency_key","item_availability_queries","item_availability_updates","push_notification_config","validation_mode"]) as readonly string[],
    __type: null as unknown as SyncCatalogsRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/creative/sync-creatives-request.json */
  SyncCreativesRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","assignment_operations","assignments","context","creative_ids","creatives","delete_missing","dry_run","ext","idempotency_key","push_notification_config","validation_mode"]) as readonly string[],
    __type: null as unknown as SyncCreativesRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/sync-event-sources-request.json */
  SyncEventSourcesRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","context","delete_missing","event_sources","ext","idempotency_key"]) as readonly string[],
    __type: null as unknown as SyncEventSourcesRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/account/sync-governance-request.json */
  SyncGovernanceRequest: Object.freeze({
    fields: Object.freeze(["accounts","adcp_major_version","adcp_version","context","ext","idempotency_key"]) as readonly string[],
    __type: null as unknown as SyncGovernanceRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/governance/sync-plans-request.json */
  SyncPlansRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","context","ext","idempotency_key","plans"]) as readonly string[],
    __type: null as unknown as SyncPlansRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/collection/update-collection-list-request.json */
  UpdateCollectionListRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","base_collections","brand","context","description","ext","filters","idempotency_key","list_id","name","webhook_url"]) as readonly string[],
    __type: null as unknown as UpdateCollectionListRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/content-standards/update-content-standards-request.json */
  UpdateContentStandardsRequest: Object.freeze({
    fields: Object.freeze(["adcp_major_version","adcp_version","calibration_exemplars","context","ext","idempotency_key","policies","registry_policy_ids","scope","standards_id"]) as readonly string[],
    __type: null as unknown as UpdateContentStandardsRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/media-buy/update-media-buy-request.json */
  UpdateMediaBuyRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","bidding","budget_allocation","budget_cap_timezone","canceled","cancellation_reason","context","daily_budget_cap","end_time","ext","governance_context","idempotency_key","invoice_recipient","media_buy_id","name","new_packages","pacing","packages","paused","push_notification_config","reporting_webhook","revision","start_time","total_budget"]) as readonly string[],
    __type: null as unknown as UpdateMediaBuyRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/mcp/2026-07-28/profiles/production/property/update-property-list-request.json */
  UpdatePropertyListRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","base_properties","brand","context","description","ext","filters","idempotency_key","list_id","name","webhook_url"]) as readonly string[],
    __type: null as unknown as UpdatePropertyListRequest,
  }),
  /** schemas/cache/3.2.0-beta.3/brand/update-rights-request.json */
  UpdateRightsRequest: Object.freeze({
    fields: Object.freeze(["account","adcp_major_version","adcp_version","context","end_date","ext","governance_context","idempotency_key","impression_cap","paused","pricing_option_id","push_notification_config","rights_id"]) as readonly string[],
    __type: null as unknown as UpdateRightsRequest,
  }),
} as const);

export type WireSpecRequestName = keyof typeof WIRE_SPEC_FIELDS;
