import { readFileSync, writeFileSync } from 'node:fs';
import { format } from 'prettier';

const version = readFileSync('ADCP_VERSION', 'utf8').trim();
const schema = (path: string) => JSON.parse(readFileSync(`schemas/cache/${version}/${path}.json`, 'utf8'));
const actions = schema('core/canonical-media-buy-action');
const tasks: Record<string, string[]> = {};
for (const branch of actions.oneOf) {
  for (const action of branch.properties.action.enum) {
    (tasks[action] ??= []).push(branch.properties.task.const);
  }
}
const compatibility =
  schema('media-buy/change-term')['x-adcp-validation'].verifier_constraints.constraint_action_compatibility;
delete compatibility.on_violation;
const text = `// Generated by scripts/generate-media-buy-action-metadata.ts from the pinned AdCP bundle.
// Runtime data only: buyer browser bundles never load JSON schemas or Node APIs.
export const CANONICAL_ACTION_TASKS = ${JSON.stringify(tasks)} as const;
export const CHANGE_CONSTRAINT_ACTIONS = ${JSON.stringify(compatibility)} as const;
export const LEGACY_AVAILABLE_ACTIONS = ${JSON.stringify(schema('enums/media-buy-valid-action').enum)} as const;
export const CHANGE_TERM_ACTIONS = ${JSON.stringify(schema('enums/canonical-media-buy-action').enum)} as const;
`;
async function main(): Promise<void> {
  const source = await format(text, { parser: 'typescript', singleQuote: true, printWidth: 110 });
  writeFileSync('src/lib/media-buy/action-metadata.generated.ts', source);
}
main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
