// Generated by scripts/generate-media-buy-update-fields.ts.
// Source: schemas/cache/<adcp_version>/enums/media-buy-valid-action.json (enumMetadata).
// Do not hand-edit - regenerate after a schema bump.

import type { MediaBuyValidAction } from './types';

export interface UpdateFieldEntry {
  /** Dotted paths into the update_media_buy request body this action covers. */
  readonly update_fields: readonly string[];
  /** Fine-grained values this action rolls up to (legacy coarse actions only). */
  readonly rollup: readonly MediaBuyValidAction[] | null;
  /** True for `x-deprecated-enum-values` (legacy coarse vocabulary). */
  readonly deprecated: boolean;
}

export const UPDATE_FIELDS_BY_ACTION: Readonly<
  Record<MediaBuyValidAction, UpdateFieldEntry>
> = {
  "pause": {
    update_fields: ["paused"] as const,
    rollup: null,
    deprecated: false,
  },
  "resume": {
    update_fields: ["paused"] as const,
    rollup: null,
    deprecated: false,
  },
  "cancel": {
    update_fields: ["canceled", "cancellation_reason"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_name": {
    update_fields: ["name"] as const,
    rollup: null,
    deprecated: false,
  },
  "extend_flight": {
    update_fields: ["end_time", "packages[].end_time"] as const,
    rollup: null,
    deprecated: false,
  },
  "shorten_flight": {
    update_fields: ["end_time", "packages[].end_time"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_flight_dates": {
    update_fields: ["start_time", "end_time", "packages[].start_time", "packages[].end_time"] as const,
    rollup: null,
    deprecated: false,
  },
  "increase_budget": {
    update_fields: ["total_budget", "packages[].budget"] as const,
    rollup: null,
    deprecated: false,
  },
  "decrease_budget": {
    update_fields: ["total_budget", "packages[].budget"] as const,
    rollup: null,
    deprecated: false,
  },
  "reallocate_budget": {
    update_fields: ["packages[].budget"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_budget_allocation": {
    update_fields: ["budget_allocation", "packages[].min_spend_target"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_targeting": {
    update_fields: ["packages[].targeting_overlay", "packages[].keyword_targets_add", "packages[].keyword_targets_remove", "packages[].negative_keywords_add", "packages[].negative_keywords_remove"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_pacing": {
    update_fields: ["pacing", "packages[].pacing"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_bidding": {
    update_fields: ["bidding", "packages[].bidding"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_frequency_caps": {
    update_fields: ["packages[].targeting_overlay.frequency_cap"] as const,
    rollup: null,
    deprecated: false,
  },
  "replace_creative": {
    update_fields: ["packages[].creatives"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_creative_assignments": {
    update_fields: ["packages[].creative_assignments"] as const,
    rollup: null,
    deprecated: false,
  },
  "remove_creative": {
    update_fields: ["packages[].creatives", "packages[].creative_assignments"] as const,
    rollup: null,
    deprecated: false,
  },
  "add_packages": {
    update_fields: ["new_packages"] as const,
    rollup: null,
    deprecated: false,
  },
  "remove_packages": {
    update_fields: ["packages[].canceled"] as const,
    rollup: null,
    deprecated: false,
  },
  "update_budget": {
    update_fields: ["total_budget", "budget_allocation", "packages[].budget", "packages[].min_spend_target"] as const,
    rollup: ["increase_budget", "decrease_budget", "reallocate_budget", "update_budget_allocation"] as const,
    deprecated: true,
  },
  "update_dates": {
    update_fields: ["start_time", "end_time", "packages[].start_time", "packages[].end_time"] as const,
    rollup: ["extend_flight", "shorten_flight", "update_flight_dates"] as const,
    deprecated: true,
  },
  "update_packages": {
    update_fields: ["packages[]"] as const,
    rollup: ["update_targeting", "update_pacing", "update_bidding", "update_frequency_caps", "reallocate_budget", "remove_packages"] as const,
    deprecated: true,
  },
  "sync_creatives": {
    update_fields: ["packages[].creatives", "packages[].creative_assignments"] as const,
    rollup: ["replace_creative", "update_creative_assignments", "remove_creative"] as const,
    deprecated: true,
  },
} as const;

export const ACTIONS_BY_FIELD: Readonly<
  Record<string, readonly MediaBuyValidAction[]>
> = {
  "bidding": ["update_bidding"] as const,
  "budget_allocation": ["update_budget_allocation"] as const,
  "canceled": ["cancel"] as const,
  "cancellation_reason": ["cancel"] as const,
  "end_time": ["extend_flight", "shorten_flight", "update_flight_dates"] as const,
  "name": ["update_name"] as const,
  "new_packages": ["add_packages"] as const,
  "pacing": ["update_pacing"] as const,
  "packages[].bidding": ["update_bidding"] as const,
  "packages[].budget": ["increase_budget", "decrease_budget", "reallocate_budget"] as const,
  "packages[].canceled": ["remove_packages"] as const,
  "packages[].creative_assignments": ["update_creative_assignments", "remove_creative"] as const,
  "packages[].creatives": ["replace_creative", "remove_creative"] as const,
  "packages[].end_time": ["extend_flight", "shorten_flight", "update_flight_dates"] as const,
  "packages[].keyword_targets_add": ["update_targeting"] as const,
  "packages[].keyword_targets_remove": ["update_targeting"] as const,
  "packages[].min_spend_target": ["update_budget_allocation"] as const,
  "packages[].negative_keywords_add": ["update_targeting"] as const,
  "packages[].negative_keywords_remove": ["update_targeting"] as const,
  "packages[].pacing": ["update_pacing"] as const,
  "packages[].start_time": ["update_flight_dates"] as const,
  "packages[].targeting_overlay": ["update_targeting"] as const,
  "packages[].targeting_overlay.frequency_cap": ["update_frequency_caps"] as const,
  "paused": ["pause", "resume"] as const,
  "start_time": ["update_flight_dates"] as const,
  "total_budget": ["increase_budget", "decrease_budget"] as const,
} as const;

export { LEGACY_COARSE_ACTIONS } from './types';
export type { LegacyCoarseAction } from './types';
